### ISSUE TITLE
Class

### ISSUE THREAD

**Issue by VB10** [CanArslanDev/flutter_chatgpt4_fullstack#2]
https://github.com/CanArslanDev/flutter_chatgpt4_fullstack/blob/ba9d32ebc143c781826a8a2976cdf696f7300814/lib/ui/shared/text_style.dart#L5

hiçbir zaman için classın içinde olmayan bir değişken kullanma bunları hep class içiine al ve static atabilirsin ardınadn başına

**Comment by CanArslanDev** [comment]
Tamamdır Veli abi bu issiueları yavaş yavaş düzelteceğim.
