### ISSUE TITLE
genel

### ISSUE THREAD

**Issue by VB10** [CanArslanDev/flutter_chatgpt4_fullstack#8]
eline sağlık bunları hemen analmasan bile başlıkları araştır doğru düşünceyi ara zamanla oturur
build dosyasını ignore al ki gelmesin çok yer kaplar
ds store dosyalarında aynı şekilde

**Comment by CanArslanDev** [comment]
Veli abi bu kadar projemi inceleyip issue açtığın için çok teşekkür ederim bunlar kendimi geliştirmek için gerçekten çok önemli. Bütün başlıkları inceleyip düşünceyi öğrenip projeye dahil edeceğim.
